development:
  narrative_base_url: localhost:8081
  weekly_reach_base_url: localhost:8082
  todays_activity_base_url: localhost:8083
production:
  narrative_base_url: localhost:8081
  weekly_reach_base_url: localhost:8082
  todays_activity_base_url: localhost:8083
test:
  narrative_base_url: localhost:8081
  weekly_reach_base_url: localhost:8082
  todays_activity_base_url: localhost:8083
