weekly_reach_base_url: datainsight-weekly-reach-recorder
todays_activity_base_url: datainsight-todays-activity-recorder
format_success_base_url: datainsight-format-success-recorder
inside_government_base_url: datainsight-insidegov-recorder
