# Add feature toggles with the format:
# <feature_name>: off|dev|release
use_tabular_numbers: release
show_weekly_visitors_in_narrative: release
inside_government_dashboard: release
inside_government_annotations: dev
